import type { CustomFieldDefinition, CustomRecipeDraft } from '@scrapestudio/extraction-core';

export const CODE_GENERATION_TARGETS = ['python', 'javascript'] as const;

export type CodeGenerationTarget = (typeof CODE_GENERATION_TARGETS)[number];

export type CodeGenerationErrorCode =
  'credentialed_url' | 'empty_recipe' | 'invalid_url' | 'unsupported_protocol';

export class CodeGenerationError extends Error {
  readonly code: CodeGenerationErrorCode;

  constructor(code: CodeGenerationErrorCode, message: string) {
    super(message);
    this.name = 'CodeGenerationError';
    this.code = code;
  }
}

export interface GeneratedStarterCode {
  code: string;
  extension: 'js' | 'py';
  redactedQueryParameters: string[];
  target: CodeGenerationTarget;
}

export interface GenerateStarterCodeInput {
  recipe: CustomRecipeDraft;
  target: CodeGenerationTarget;
  targetUrl: string;
}

const SENSITIVE_QUERY_KEY =
  /(?:^|[_.-])(api[_-]?key|auth|authorization|credential|jwt|password|secret|session|signature|token)(?:$|[_.-])/i;
const REDACTED_VALUE = 'REPLACE_WITH_VALUE';

function normalizedRecipe(recipe: CustomRecipeDraft): CustomRecipeDraft {
  const itemSelector = recipe.itemSelector.trim();
  const fields = recipe.fields.map((field) => ({
    ...field,
    ...(field.attribute === undefined ? {} : { attribute: field.attribute.trim() }),
    name: field.name.trim(),
    selector: field.selector.trim(),
  }));

  if (!itemSelector || fields.length === 0) {
    throw new CodeGenerationError(
      'empty_recipe',
      'A non-empty item selector and at least one field are required.',
    );
  }

  return { fields, itemSelector };
}

function safeTargetUrl(input: string): { redactedQueryParameters: string[]; url: string } {
  let url: URL;
  try {
    url = new URL(input);
  } catch {
    throw new CodeGenerationError('invalid_url', 'The target URL is invalid.');
  }

  if (url.protocol !== 'http:' && url.protocol !== 'https:') {
    throw new CodeGenerationError(
      'unsupported_protocol',
      'Only HTTP and HTTPS target URLs can be generated.',
    );
  }
  if (url.username || url.password) {
    throw new CodeGenerationError(
      'credentialed_url',
      'Credentialed target URLs cannot be included in generated code.',
    );
  }

  const redactedQueryParameters: string[] = [];
  for (const key of [...new Set(url.searchParams.keys())]) {
    if (SENSITIVE_QUERY_KEY.test(key)) {
      url.searchParams.set(key, REDACTED_VALUE);
      redactedQueryParameters.push(key);
    }
  }
  url.hash = '';

  return { redactedQueryParameters, url: url.href };
}

function jsLiteral(value: string): string {
  return JSON.stringify(value)
    .replaceAll('<', '\\u003c')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029');
}

function pythonString(value: string): string {
  return jsLiteral(value);
}

function pythonOptionalString(value: string | undefined): string {
  return value === undefined ? 'None' : pythonString(value);
}

function pythonField(field: CustomFieldDefinition): string {
  return [
    '    {',
    `        "name": ${pythonString(field.name)},`,
    `        "selector": ${pythonString(field.selector)},`,
    `        "mode": ${pythonString(field.mode)},`,
    `        "attribute": ${pythonOptionalString(field.attribute)},`,
    `        "fallback": ${pythonOptionalString(field.fallback)},`,
    `        "multiple": ${field.multiple === true ? 'True' : 'False'},`,
    `        "trim": ${field.trim === false ? 'False' : 'True'},`,
    '    },',
  ].join('\n');
}

function generatePython(targetUrl: string, recipe: CustomRecipeDraft): string {
  const fields = recipe.fields.map(pythonField).join('\n');
  return `# Generated by ScrapeStudio from the active local recipe.
# Install: python -m pip install requests beautifulsoup4
# Static HTML only. JavaScript-rendered or protected pages may need a different,
# site-authorized approach. This starter does not bypass access controls.
# Review the target site's terms and robots policy before running it.

import json
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup

TARGET_URL = ${pythonString(targetUrl)}
ITEM_SELECTOR = ${pythonString(recipe.itemSelector)}
TIMEOUT_SECONDS = 10
MAX_ITEMS = 200
MAX_VALUES_PER_FIELD = 100
HEADERS = {
    "User-Agent": "ScrapeStudio-Starter/1.0 (responsible public-page extraction)"
}
FIELDS = [
${fields}
]


def selected_nodes(item, selector):
    return [item] if selector == ":scope" else item.select(selector)


def string_value(node, field):
    mode = field["mode"]
    if mode == "attribute":
        raw = node.get(field["attribute"] or "")
    elif mode == "href":
        raw = urljoin(TARGET_URL, node.get("href")) if node.get("href") else None
    elif mode == "src":
        raw = urljoin(TARGET_URL, node.get("src")) if node.get("src") else None
    elif mode == "html":
        # Keep as untrusted text; never insert this value directly into a live page.
        raw = node.decode_contents()
    else:
        raw = node.get_text(" ", strip=False)

    if raw is None:
        return field["fallback"]
    value = raw.strip() if field["trim"] else raw
    return value if value or field["fallback"] is None else field["fallback"]


def extract_field(item, field):
    nodes = selected_nodes(item, field["selector"])
    if field["mode"] == "count":
        return len(nodes)
    if field["mode"] == "exists":
        return bool(nodes)
    if field["multiple"]:
        values = [string_value(node, field) for node in nodes[:MAX_VALUES_PER_FIELD]]
        return [value for value in values if value not in (None, "")]
    return string_value(nodes[0], field) if nodes else field["fallback"]


def main():
    # No cookies, credentials, authorization headers, or anti-bot bypass are included.
    response = requests.get(
        TARGET_URL,
        headers=HEADERS,
        timeout=TIMEOUT_SECONDS,
        allow_redirects=True,
    )
    response.raise_for_status()
    if "html" not in response.headers.get("content-type", "").lower():
        raise ValueError("Expected an HTML response")

    soup = BeautifulSoup(response.text, "html.parser")
    rows = []
    for item in soup.select(ITEM_SELECTOR)[:MAX_ITEMS]:
        rows.append({field["name"]: extract_field(item, field) for field in FIELDS})
    print(json.dumps(rows, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
`;
}

function generateJavaScript(targetUrl: string, recipe: CustomRecipeDraft): string {
  const serializedRecipe = JSON.stringify(recipe, null, 2)
    .replaceAll('<', '\\u003c')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029');
  return `// Generated by ScrapeStudio from the active local recipe.
// Requires Node.js 20+ and linkedom: npm install linkedom
// Static HTML only. JavaScript-rendered or protected pages may need a different,
// site-authorized approach. This starter does not bypass access controls.
// Review the target site's terms and robots policy before running it.

import { parseHTML } from "linkedom";

const TARGET_URL = ${jsLiteral(targetUrl)};
const RECIPE = ${serializedRecipe};
const TIMEOUT_MS = 10_000;
const MAX_ITEMS = 200;
const MAX_VALUES_PER_FIELD = 100;

function selectedNodes(item, selector) {
  return selector === ":scope" ? [item] : [...item.querySelectorAll(selector)];
}

function stringValue(node, field) {
  let raw;
  switch (field.mode) {
    case "attribute":
      raw = node.getAttribute(field.attribute ?? "");
      break;
    case "href":
    case "src": {
      const reference = node.getAttribute(field.mode);
      raw = reference ? new URL(reference, TARGET_URL).href : null;
      break;
    }
    case "html":
      // Keep as untrusted text; never insert this value directly into a live page.
      raw = node.innerHTML;
      break;
    case "innerText":
      raw = node.innerText ?? node.textContent;
      break;
    default:
      raw = node.textContent;
  }

  if (raw === null || raw === undefined) return field.fallback ?? null;
  const value = field.trim === false ? raw : raw.trim();
  return value || field.fallback || value;
}

function extractField(item, field) {
  const nodes = selectedNodes(item, field.selector);
  if (field.mode === "count") return nodes.length;
  if (field.mode === "exists") return nodes.length > 0;
  if (field.multiple) {
    return nodes
      .slice(0, MAX_VALUES_PER_FIELD)
      .map((node) => stringValue(node, field))
      .filter((value) => value !== null && value !== "");
  }
  return nodes[0] ? stringValue(nodes[0], field) : (field.fallback ?? null);
}

async function main() {
  // No cookies, credentials, authorization headers, or anti-bot bypass are included.
  const response = await fetch(TARGET_URL, {
    headers: {
      "user-agent": "ScrapeStudio-Starter/1.0 (responsible public-page extraction)",
    },
    redirect: "follow",
    signal: AbortSignal.timeout(TIMEOUT_MS),
  });
  if (!response.ok) throw new Error(\`HTTP \${response.status}\`);
  if (!(response.headers.get("content-type") ?? "").toLowerCase().includes("html")) {
    throw new Error("Expected an HTML response");
  }

  const html = await response.text();
  const { document } = parseHTML(html);
  const items = [...document.querySelectorAll(RECIPE.itemSelector)].slice(0, MAX_ITEMS);
  const rows = items.map((item) =>
    Object.fromEntries(RECIPE.fields.map((field) => [field.name, extractField(item, field)])),
  );
  console.log(JSON.stringify(rows, null, 2));
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : "Extraction failed");
  process.exitCode = 1;
});
`;
}

export function generateStarterCode(input: GenerateStarterCodeInput): GeneratedStarterCode {
  const recipe = normalizedRecipe(input.recipe);
  const { redactedQueryParameters, url } = safeTargetUrl(input.targetUrl);
  return input.target === 'python'
    ? {
        code: generatePython(url, recipe),
        extension: 'py',
        redactedQueryParameters,
        target: input.target,
      }
    : {
        code: generateJavaScript(url, recipe),
        extension: 'js',
        redactedQueryParameters,
        target: input.target,
      };
}
